### ISSUE TITLE
BidRevealed statuses undocumented

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens#171] opened 2017-05-06 11:25 UTC
The `BidRevealed` event has a status code which goes from 0 to 5

```
    event BidRevealed(bytes32 indexed hash, address indexed owner, uint value, uint8 status);
```

In the source code hardcoded numerical constants are used. Would it be better to label those constants, simultaneously documenting what the status mean?

**Comment by Arachnid** [comment] 2017-05-06 12:09
Duplicate of #147 .

**Closed by Arachnid** 2017-05-06 12:09 UTC
